### ISSUE TITLE
gh pages as default branch

### ISSUE THREAD

**Issue by abhinavk96** [BitNotes-CwayProduction/Frontend#3]
@BelieveC  should we make gh-pages as the default branch, will be easier to work in collabration while working on frontEnd?

**Comment by BelieveC** [comment]
Ohk, we would make gh-pages @CosmicCoder96

**Comment by BelieveC** [comment]
I have made gh-pages. We can push directly to gh-pages branch. We would work on gh-pages branch as default branch.
